#!/bin/bash

echo "======================================"
echo "  SUBIR A GITHUB - veamos-que-sale"
echo "======================================"
echo ""
echo "📋 INSTRUCCIONES:"
echo ""
echo "1. Crea el repositorio en GitHub:"
echo "   - Ve a: https://github.com/new"
echo "   - Nombre: veamos-que-sale"
echo "   - Descripción: no se xd"
echo "   - Tipo: Public"
echo "   - NO marcar 'Initialize with README'"
echo ""
echo "2. Ejecuta estos comandos:"
echo ""
echo "   cd /data/data/com.termux/files/home/lg_webos_rooting/lg_remote_android_v2"
echo ""
echo "   # Reemplaza TU_USUARIO con tu usuario de GitHub"
echo "   git remote add origin https://github.com/TU_USUARIO/veamos-que-sale.git"
echo ""
echo "   # Cambiar a branch main"
echo "   git branch -M main"
echo ""
echo "   # Subir código (te pedirá usuario y token)"
echo "   git push -u origin main"
echo ""
echo "3. Cuando pida password, usa tu Personal Access Token:"
echo "   - GitHub → Settings → Developer settings"
echo "   - Personal access tokens → Tokens (classic)"
echo "   - Generate new token (classic)"
echo "   - Permisos: repo (completo) + workflow"
echo ""
echo "4. GitHub Actions compilará automáticamente:"
echo "   - Ve a: https://github.com/TU_USUARIO/veamos-que-sale/actions"
echo "   - Espera 5-10 minutos"
echo "   - Descarga APK desde Releases"
echo ""
echo "======================================"
echo ""
echo "El repositorio ya está listo con:"
echo "  ✅ Código completo (675 líneas Kotlin)"
echo "  ✅ GitHub Actions configurado"
echo "  ✅ .gitignore configurado"
echo "  ✅ Documentación completa"
echo "  ✅ Git inicializado con commit"
echo ""
echo "Solo falta conectar con GitHub y push!"
echo ""
